### PR TITLE
Chore: Removing deprecated models (cloud free and trial requests)

### PR DESCRIPTION
**Pull request by munish7771**
#### Summary

Removing the models under as they will be deprecated after the new release. 
1. hightouch/freemium/cloud_starter/*
2. hightouch/freemium/etr/*

There is an exception for model `hightouch/freemium/cloud_starter/cs_signup_campaign_facts` which is used by a downstream model in `data quality` layer and is not removed.

#### Ticket Link

N/A
This PR is among the deployment steps for -> https://github.com/mattermost/mattermost-data-warehouse/pull/1265

#### Deployment steps
- [ ] Move the tables to archive with lifecycle of 30 days in snowflake.
- [x] Disable/Delete the downstream Hightouch syncs.

### CODE REVIEW

**Comment by catalintomai** [comment]
@munish7771 , wrt to "There is an exception for model hightouch/freemium/cloud_starter/cs_signup_campaign_facts which is used by a downstream model in data quality layer and is not removed." - would it make sense to move that model out of the freemium folder, if it is independent of cloud starter/free logic (and completely remove the freemium folder)?

**Comment by johndavidlugtu** [comment]
@nickmisasi anything worth calling out here?

**Review by nickmisasi — APPROVED** [review]
@johndavidlugtu this is all downstream from us so no concerns from me

**Comment by catalintomai** [comment]
@munish7771 , let's move the "trial-requests" removal code from here and make it part of the work for addressing https://mattermost.atlassian.net/browse/MM-52595. Thanks.

**Comment by catalintomai** [comment]
@munish7771 , would this be the opportunity to remove the blapi `customers_with_freemium_subs.sql` model?

**Comment by munish7771** [comment]
> @munish7771 , would this be the opportunity to remove the blapi `customers_with_freemium_subs.sql` model?

Can't remove it unless we remove the downstream model `cancelled_update_opportunity` as well.

**Pull request merged**
