### PR TITLE
MM-45774 cloud starter bug

### PR DESCRIPTION
**Pull request by munish7771**
#### Summary
Issue - Cloud starter models are not getting status = "Email verified" due to depreciated event in telemetry. Also, some leads are not getting synced over to salesforce.
Updates -
1.Updated the fact table to use new event thats triggered after user successfully enters valid email code. Validated the no of users with status "Email Verified".
2. Added new event names for syncing missing leads.

#### Ticket Link
https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/104?modal=detail&selectedIssue=MM-45774
https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/104?modal=detail&selectedIssue=MM-45622

### CODE REVIEW

**Review by nat-gunner — COMMENTED** [review]
looks good to me!
just to confirm: the backfill won't overwrite any "Workspace Created" statuses with "Email Verified" statuses, right?

**Comment by munish7771** [comment]
> looks good to me! just to confirm: the backfill won't overwrite any "Workspace Created" statuses with "Email Verified" statuses, right?

I will not overwrite "Workspace Created" status. But it will convert some of the existing leads in "Account Created" to "Email Verified".

**Comment by munish7771** [comment]
@nat-gunner @catalintomai please approve this PR.

**Review by nat-gunner — APPROVED** [review]
sounds good @munish7771 !

**Review by catalintomai — APPROVED** [review]

**Pull request merged**
