### PR TITLE
MM-61128: Add dbt models to support server configuration dashboards

### PR DESCRIPTION
**Pull request by catalintomai**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61128

### CODE REVIEW

**Review by ifoukarakis — COMMENTED** [review]
Would be nice to add documentation for new models and update for `dim_daily_server_config`.

**Comment by catalintomai** [comment]
> Would be nice to add documentation for new models and update for `dim_daily_server_config`.

Added fields. Fields description needs (a lot) more work, so we'll add at a later date.

**Review by ifoukarakis — APPROVED** [review]

**Comment by ifoukarakis** [comment]
Approving. Let's work on improving docs both for staging and dimension models.

**Comment by catalintomai** [comment]
> Approving. Let's work on improving docs both for staging and dimension models.

Thanks for reminding me to add documentation to the staging models as well. Will add them as well.

**Pull request merged**
