### PR TITLE
MM-42949: Creating Scripts for LTV for EMEA APAC and ROW

### PR DESCRIPTION
**Pull request by RoyI99**
#### Summary

Introduces a new model for testing for missing activity data. This PR contains the following items:
- [x] Extending LTV analyses to the other regions EMEA APAC and ROW
- [x] Creating three model files arr_ltv_emea.sql, arr_ltv_apac.sql and arr_ltv_row.sql
- [x] Tested in dbt local environment 
- [x] Looker PR -> [pr-mattermost-looker-895](https://github.com/mattermost/mattermost-looker/pull/895)

Ticket link 
https://mattermost.atlassian.net/browse/MM-49259

### CODE REVIEW

**Comment by RoyI99** [comment]
All ran successfully with dbt run

**Comment by RoyI99** [comment]
royi99@X12RIG:/mnt/c/Users/royib/Documents/MM2/mattermost-data-warehouse$ make dbt-bash
09:48:23 [ .. ] Running bash with dbt...
17:48:28  Running with dbt=1.0.0
17:48:29  Installing version 0.8.6
17:48:37    Installed from version 0.8.6
17:48:37    Updated version available: 1.0.0
17:48:37  
17:48:37  Updates available for packages: ['dbt-labs/dbt_utils']
Update your versions in packages.yml, then run dbt deps
root@a71081375ead:/usr/app/dbt# dbt run --m models/finance/arr_ltv_emea.sql
17:49:10  Running with dbt=1.0.0
17:49:20  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.mm_snowflake.ga
- seeds.mm_snowflake.snowflake_contract_rates

17:49:20  Found 293 models, 11 tests, 0 snapshots, 0 analyses, 432 macros, 0 operations, 15 seed files, 264 sources, 0 exposures, 0 metrics
17:49:20  
17:49:37  Concurrency: 8 threads (target='prod')
17:49:37
17:49:37  1 of 1 START table model finance.arr_ltv_emea................................... [RUN]
17:49:41  1 of 1 OK created table model finance.arr_ltv_emea.............................. [SUCCESS 1 in 4.52s]
17:49:41
17:49:41  Finished running 1 table model in 21.34s.
17:49:41  
17:49:41  Completed successfully
17:49:41
17:49:41  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
root@a71081375ead:/usr/app/dbt# dbt run --m models/finance/arr_ltv_apac.sql
18:00:11  Running with dbt=1.0.0
18:00:19  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.mm_snowflake.ga
- seeds.mm_snowflake.snowflake_contract_rates

18:00:19  Found 295 models, 11 tests, 0 snapshots, 0 analyses, 432 macros, 0 operations, 15 seed files, 264 sources, 0 exposures, 0 metrics
18:00:19  
18:00:33  Concurrency: 8 threads (target='prod')
18:00:33
18:00:33  1 of 1 START table model finance.arr_ltv_apac................................... [RUN]
18:00:37  1 of 1 OK created table model finance.arr_ltv_apac.............................. [SUCCESS 1 in 4.35s]
18:00:37
18:00:37  Finished running 1 table model in 18.58s.
18:00:38  
18:00:38  Completed successfully
18:00:38
18:00:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
root@a71081375ead:/usr/app/dbt# dbt run --m models/finance/arr_ltv_row.sql
18:01:08  Running with dbt=1.0.0
18:01:15  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.mm_snowflake.ga
- seeds.mm_snowflake.snowflake_contract_rates

18:01:16  Found 295 models, 11 tests, 0 snapshots, 0 analyses, 432 macros, 0 operations, 15 seed files, 264 sources, 0 exposures, 0 metrics
18:01:16  
18:01:34  Concurrency: 8 threads (target='prod')
18:01:34
18:01:34  1 of 1 START table model finance.arr_ltv_row.................................... [RUN]
18:01:38  1 of 1 OK created table model finance.arr_ltv_row............................... [SUCCESS 1 in 3.45s]
18:01:38
18:01:38  Finished running 1 table model in 22.04s.
18:01:38  
18:01:38  Completed successfully
18:01:38
18:01:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
root@a71081375ead:/usr/app/dbt#

**Review by munish7771 — CHANGES_REQUESTED** [review]
Can you push the documentation in schema.yml

**Review by munish7771 — APPROVED** [review]
Looks good !

**Pull request merged**
